insert cdn domain into all assets/img/ urls
netz39/www.netz39.de pull request #140
Opened 2024-11-05 20:18 UTC by teuserer

Dieser PR ist abhängig von https://github.com/penguineer/cdn.netz39.de/pull/4

Die Gallerie ist hiermit leer. https://www.netz39.de/gallery/
Sie scheint aber auch nicht genutzt worden zu sein.

2024-12-12 20:39 UTC, AOphagen approved these changes
Passt.

2024-12-12 20:41 UTC, AOphagen approved these changes
Nein, ich habe nicht alle 354 Dateien einzeln angeschaut, aber den Anfang, das Ende und einige Stichproben. Passt.

2024-12-12 21:30 UTC, penguineer requested changes
Sehe ich richtig, dass Du vor allem die URL-Pattern angepasst hast? Ich sehe in der ersten URL schon ein 404 - bitte nochmal prüfen, ob da ggf. zu viel geändert wurde.

2024-12-12 21:30 UTC, penguineer commented on README.md
> +        feature-img: "https://cdn.netz39.de/img/feature-img.jpg" # optional
Diese URL gibt direkt ein 404

2024-12-19 01:50 UTC, MG-5 commented on README.md
> +        feature-img: "https://cdn.netz39.de/img/feature-img.jpg" # optional
Das ist nur ein Beispiel in der ReadMe

2024-12-19 01:52 UTC, MG-5 approved these changes
Stichpunktartige Probe sahen gut aus

2024-12-19 01:56 UTC, merged