Export ics feed
netz39/www.netz39.de pull request #45
Opened 2023-10-25 13:52 UTC by MG-5

2023-10-25 17:42 UTC, LeSpocky commented
Wie werden diese assets wie bspw. jquery später aktuell gehalten?

2023-10-26 00:58 UTC, MG-5 commented
> Wie werden diese assets wie bspw. jquery später aktuell gehalten?

https://docs.renovatebot.com/modules/manager/html/

2023-10-26 07:28 UTC, 24367dfa commented
> > Wie werden diese assets wie bspw. jquery später aktuell gehalten?
> 
> https://docs.renovatebot.com/modules/manager/html/

das ist nicht ganz, wie der renovate bot funktioniert :-) Da wir hier die dependencies explizit rein kopiert haben, kann der renovate da nicht viel mit anfangen. Wenn wir eine Datei hätten, in der wir beschreiben, welche Version wir beim Ausliefern der Seite mit rein backen, wäre das ein Anwendunsfall für den Renovatebot.

2023-10-26 08:13 UTC, 24367dfa requested changes
Ich hätte gern noch irgendwo einen Vermerk, woher die Javascript Schnipsel kommen und wo man entsprechend in Zukunft nach Updates suchen müsste.

Zb ein readme im assets/js/vendor Ordner. Nebenbei, wie sieht es da mit den Lizenzen aus?

2023-10-26 10:20 UTC, LeSpocky commented
Es gibt hier im Projekt ja schon *assets/package.json* ... hilft uns das weiter? Wie wird das benutzt und kann man da nicht sowas wie jquery mit eintragen? Zumindest der Depandabot von GitHub liest solche files wohl aus, richtig?

2023-10-27 16:21 UTC, 24367dfa commented
> Es gibt hier im Projekt ja schon _assets/package.json_ ... hilft uns das weiter? Wie wird das benutzt und kann man da nicht sowas wie jquery mit eintragen? Zumindest der Depandabot von GitHub liest solche files wohl aus, richtig?

Nicht wirklich, das sind so weit ich das sehe die dependencies für einen build step und nicht für die Auslieferung mit der Website. Aber ich würde sowohl das Lizenz- als auch das Aktualisierungsthema in ein seprates Issue auslagern, damit wir mit Max' Änderung schnell weiter kommen.

2023-11-04 07:18 UTC, 24367dfa commented
Ich glaube, die Anforderung von Alex war nicht hinreichend präzise gestellt. Ich denke, dass die Lösung eher so aussehen müsste, wie die Erzeugung der Suchseite oder der Tags. Also das Zusammenbauen einer statischen Ressource aus den Dateien in `_events` während des jekyll build Prozesses.

2023-11-04 12:15 UTC, MG-5 commented
Die Umsetzung von DAvid finde ich sehr gut, sodasss ich das als die bessere Alternative sehe - deswegen schließe ich den PR ohne Merge.

2023-11-04 12:15 UTC, closed without merging