Events/freies hacken
netz39/www.netz39.de pull request #74
Opened 2023-11-06 10:55 UTC by timherrm

2023-11-06 11:01 UTC, MG-5 commented
Wie in Issue schon geschrieben: Für mich ist das keine gute Idee, jeden Mittwoch mit Freies Hacken zu belegen, weil mein Kalender dann unübersichtlich wird und ich dann wahrscheinlich deabbonnieren würde.

2023-11-06 11:16 UTC, MG-5 commented
Mir fällt grad auf, ich habe es damals versäumt, die events in Ordnern mit den Jahren zu packen. Kannst du dafür sorgen, dass sie in 2023/2024 usw Ordnern gelangen?

2023-11-06 11:17 UTC, MG-5 commented
Außerdem wollte er weder für 20224 noch für 2025 was erzeugen:

![grafik](https://github.com/netz39/www.netz39.de/assets/12341832/0ac0b659-bc34-4411-9e44-2bc719095fa4)

2023-11-06 23:34 UTC, penguineer commented
Über Tags könnte man das sortieren.

Wie im Issue auch geschrieben, bevor wir viele events generieren, die wir alle nochmal anfassen müssen, sollten wir Startzeit/Dauer klären.

2023-11-07 18:19 UTC, penguineer commented
Offtopic: Damit wir die Merges nicht wieder bekommen, sollte beim Update die Option "Update with rebase" gewählt werden. Das lässt sich leider nicht voreinstellen.

2023-11-09 10:45 UTC, timherrm commented
Ich habe jetzt die Events gelöscht und würde erstmal nur das Script in den Tools Ordner mergen. Wenn wir dann entschieden haben wie es mit den Events mit der Zeit weitergeht, dann mache ich nen neuen PR auf.

2023-11-09 10:49 UTC, 24367dfa commented
Nimm Mal das draft raus.

2023-11-09 10:55 UTC, 24367dfa commented on tools/generate_freieshacken_events.py
> +**Wann: 19:30 Uhr**\\
Die Texte sind hier gerade ganz schön statisch tief im Code verbuddelt.

2023-11-09 10:56 UTC, 24367dfa commented on tools/generate_freieshacken_events.py
> +# Calculate Wednesdays in weeks divisible by three
Passt der Kommentar hier wirklich zum Code?

2023-11-09 11:00 UTC, timherrm commented
> Nimm Mal das draft raus. Und mach Mal eine `git rebase -i main` und wirf die commits raus, die du nicht mit mergen willst.

so richtig?

2023-11-09 11:04 UTC, timherrm commented on tools/generate_freieshacken_events.py
> +# Calculate Wednesdays in weeks divisible by three
Copy-Paste Fehler.Hab ich angepasst

2023-11-09 11:05 UTC, timherrm commented on tools/generate_freieshacken_events.py
> +**Wann: 19:30 Uhr**\\
Besser als Variable ganz oben?

2023-11-09 11:12 UTC, 24367dfa commented on tools/generate_freieshacken_events.py
> +**Wann: 19:30 Uhr**\\
Ja, würde ich so machen.

2023-11-09 11:13 UTC, 24367dfa commented on tools/generate_freieshacken_events.py
> +input_year = int(input("Enter the year: "))
Ich würde das lieber in einem Argument an das Script übergeben, dann lässt sich das auch automatisiert benutzen und ist nicht auch einen interaktiven Benutzer angewiesen.

2023-11-09 11:50 UTC, timherrm commented
Dann ist das doch mal noch WIP. Der Teil, dass die Events in Jahresordnern landen fehlt auch noch.

2023-11-09 12:24 UTC, timherrm commented on tools/generate_freieshacken_events.py
> +**Wann: 19:30 Uhr**\\
done

2023-11-09 12:25 UTC, timherrm commented on tools/generate_freieshacken_events.py
> +input_year = int(input("Enter the year: "))
done

2023-11-09 12:26 UTC, timherrm commented
@24367dfa Kannst du so nochmal drüber schauen?

2023-11-09 15:53 UTC, penguineer requested changes
Das klingt vllt nach Nitpicking, aber ich habe mir inzwischen angewöhnt, für Python-Scripte immer auch einen Docker-Container zu definieren und im README die entsprechenden Aufrufe (mit Volume Mount) zu definieren. Wir tun uns damit mittel- und langfristig einen großen Gefallen.

Hintergrund ist, dass es ziemlich nervig sein kann, die passenden Dependencies im System zu haben, insbesondere weil es Bibliotheken gibt, die miteinander im Konflikt stehen.

Da auch virtual environments gerade nicht zuverlässig deploybar sind, ist ein Container die zuverlässigste Lösung.

Heißt konkret:
-  [ ] Tool-Spezifisches Verzeichnis, damit wir nicht den Überblick verlieren (`git mv`)
- [ ] Dockerfile
- [ ] Entsprechender Container-Aufruf in der README

Wenn Du dabei Unterstützung brauchst, sag bitte Bescheid.

2023-11-09 15:53 UTC, penguineer commented on tools/README.md
> +```bash
Wollen wir diesen Output wirklich im Repo haben?

2023-11-10 06:45 UTC, timherrm commented on tools/README.md
> +```bash
Mir ist das egal, ich kann es auch einfach wieder löschen. Möchte nur verstehen, was dein Gedanke dahinter ist, das zu löschen, damit ich es fürs nächste Mal weiß 😄

2023-11-10 07:43 UTC, penguineer commented on tools/README.md
> +```bash
Ich hab mich gefragt, was wir mit der Info im README machen - geht es darum, noch zu wissen, was dafür passiert ist? Dann würde ich die Info eher in die Commit-Message oder den PR schreiben.

2023-11-10 07:47 UTC, timherrm commented on tools/README.md
> +```bash
Für mich war es eher ein "so führst du es aus" und "das sollte dann dabei rauskommen, wenn alles funktioniert hat".
Hat für mich als Unwissender halt Sinn gemacht das da hin zu schreiben :D

2023-11-24 12:03 UTC, penguineer commented
@timherrm Nach dem Git-Workshop: Hast Du Lust, die Commits ein wenig zusammenzufassen? ;)

2025-04-09 23:32 UTC, MG-5 commented
Mit #71 verliert das hier an Relevanz. Kann geschlossen werden, oder?

2025-04-10 08:01 UTC, closed without merging